package com.henryxi.mybatis.mapper;

import com.henryxi.mybatis.entity.UserInfoEntity;
import com.henryxi.mybatis.entity.UserInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    int countByExample(UserInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    int deleteByExample(UserInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    int insert(UserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    int insertSelective(UserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    List<UserInfoEntity> selectByExample(UserInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    UserInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserInfoEntity record, @Param("example") UserInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserInfoEntity record, @Param("example") UserInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInfoEntity record);
}